
export const LOAD_OWNED_WALLET_SUCCESS = 'LOAD_OWNED_WALLET_SUCCESS';
export const LOAD_OWNED_WALLET_FAILURE = 'LOAD_OWNED_WALLET_FAILURE';
export const LOAD_AUTH_USER_SUCCESS = 'LOAD_AUTH_USER_SUCCESS';
export const LOAD_AUTH_USER_FAILURE = 'LOAD_AUTH_USER_FAILURE';
